import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowClockwise, ArrowDown, ArrowUpRight, Bell, CalendarBlank, CaretDown, CaretLeft, CaretRight, ChartBar, ChartLineUp, Check, CheckCircle, Clock, CloudSun, Cpu, DownloadSimple, Drop, DropHalfBottom as Drops, Gauge, GearSix, House, Info, Leaf, List, MapPin, Minus, NavigationArrow, Pause, Play, Plus, Power, Radio, MagnifyingGlass as Search, ShieldCheck, SignOut, SlidersHorizontal, DeviceMobile as Smartphone, SquaresFour, Sun, Thermometer, Timer, Trash, Warning, Waves, WifiHigh, WifiSlash, Wind, X } from '@phosphor-icons/react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from './api';
import Decision from './Decision';
import type { Alert, Plan, Settings, State, Zone } from './types';

type Page = 'overview' | 'decision' | 'zones' | 'devices' | 'plans' | 'analytics' | 'alerts' | 'settings';
type Mutation = (path: string, method?: string, body?: unknown, message?: string) => Promise<boolean>;
const navigation = [
  { id: 'overview' as Page, label: '运行总览', icon: SquaresFour },
  { id: 'zones' as Page, label: '分区灌溉', icon: Drops },
  { id: 'devices' as Page, label: '设备管理', icon: Cpu },
  { id: 'plans' as Page, label: '灌溉计划', icon: CalendarBlank },
  { id: 'decision' as Page, label: '灌溉决策', icon: ChartLineUp },
  { id: 'analytics' as Page, label: '用水分析', icon: ChartBar },
  { id: 'alerts' as Page, label: '告警中心', icon: Bell },
];
const week = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];
const number = (value: number, maximumFractionDigits = 1) => new Intl.NumberFormat('zh-CN', { maximumFractionDigits }).format(value);
const time = (value: string) => new Date(value).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Shanghai' });
const dateTime = (value: string) => new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Shanghai' });
const statusLabels = { idle: '待机', watering: '灌溉中', offline: '离线' };

function Brand({ small = false }: { small?: boolean }) {
  return <div className={`brand ${small ? 'small' : ''}`}><div className="brand-symbol"><Drop size={26} weight="fill" /><span /></div><div><strong>澜枢<span>LANSHU</span></strong><p>智慧灌溉管理平台</p></div></div>;
}

function Badge({ status, children }: { status: string; children: ReactNode }) { return <span className={`badge ${status}`}><i />{children}</span>; }
function Empty({ text, children }: { text: string; children?: ReactNode }) { return <div className="empty"><CheckCircle size={38} weight="light" /><h3>{text}</h3>{children}</div>; }

function Modal({ title, description, children, onClose, wide = false }: { title: string; description?: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const d = ref.current; d?.showModal(); return () => d?.close(); }, []);
  return <dialog ref={ref} className={`dialog ${wide ? 'wide' : ''}`} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog-head"><div><h2>{title}</h2>{description && <p>{description}</p>}</div><button className="icon-button" aria-label="关闭弹窗" onClick={onClose}><X size={21} /></button></div>{children}</dialog>;
}

function FarmMap({ zones, selected, onSelect }: { zones: Zone[]; selected: string; onSelect: (id: string) => void }) {
  const [zoom, setZoom] = useState(1);
  const plots = [
    { points: '145,92 311,64 339,162 170,199', x: 240, y: 132 },
    { points: '328,62 514,74 506,173 354,162', x: 423, y: 121 },
    { points: '532,76 711,110 673,219 526,178', x: 615, y: 151 },
    { points: '174,217 341,179 371,292 221,336', x: 277, y: 257 },
    { points: '359,182 505,190 537,303 387,294', x: 443, y: 245 },
    { points: '525,196 669,238 624,346 555,310', x: 591, y: 276 },
  ];
  return <div className="farm-map"><div className="map-label"><span className="map-live" /> 智慧农场 · 分区示意</div><div className="map-tools"><button onClick={() => setZoom(Math.min(1.5, zoom + .15))} aria-label="放大分区图"><Plus size={17} /></button><button onClick={() => setZoom(Math.max(.7, zoom - .15))} aria-label="缩小分区图"><Minus size={17} /></button><button onClick={() => setZoom(1)} aria-label="重置分区图"><NavigationArrow size={16} /></button></div><div className="north"><NavigationArrow size={18} weight="fill" /><span>N</span></div>
    <svg viewBox="0 0 820 390" role="group" aria-label="农场六个灌溉分区的示意图，点击分区查看状态">
      <defs><pattern id="map-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#d7e3e8" strokeWidth=".55" /></pattern><pattern id="crop-lines" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(-14)"><path d="M0 0V10" stroke="#88aea0" strokeWidth="1" opacity=".26" /></pattern><pattern id="blue-lines" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(-14)"><path d="M0 0V10" stroke="#1f6cdb" strokeWidth="1" opacity=".22" /></pattern></defs>
      <rect width="820" height="390" fill="url(#map-grid)" />
      <g transform={`translate(410 195) scale(${zoom}) translate(-410 -195)`}>
        <path d="M0 301C100 320 70 151 118 56S254 28 310 0M760 0C709 87 788 105 770 211S787 334 820 350" stroke="#dde9e4" fill="none" strokeWidth="38" />
        <path d="M42 390L110 331 83 187 113 24M211 390L760 58" stroke="#fff" fill="none" strokeWidth="10" />
        <path d="M94 382L143 216 339 172 512 181 696 230 770 166" stroke="#aeccec" fill="none" strokeWidth="11" strokeLinejoin="round" />
        <path d="M94 382L143 216 339 172 512 181 696 230 770 166" stroke="#f8fcff" fill="none" strokeWidth="3" strokeDasharray="6 6" />
        {zones.slice(0, 6).map((zone, index) => { const p = plots[index]; return <g key={zone.id} className={`map-plot ${zone.id === selected ? 'selected' : ''}`} role="button" tabIndex={0} aria-label={`${zone.name}，${statusLabels[zone.status]}，墒情${number(zone.moisture)}%`} onClick={() => onSelect(zone.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(zone.id); } }}>
          <polygon points={p.points} fill={zone.status === 'watering' ? '#ccdefa' : zone.status === 'offline' ? '#e5e7e7' : '#d8e8df'} stroke={zone.id === selected ? '#2567df' : zone.status === 'offline' ? '#bbc7cd' : '#b1cbbd'} strokeWidth={zone.id === selected ? 2.7 : 1.5} strokeLinejoin="round" />
          <polygon points={p.points} fill={`url(#${zone.status === 'watering' ? 'blue-lines' : 'crop-lines'})`} />
          <rect x={p.x - 53} y={p.y - 22} width="106" height="49" rx="7" fill="white" fillOpacity=".94" />
          <text x={p.x} y={p.y - 2} textAnchor="middle" fill="#24435c" fontWeight="600" fontSize="12">{zone.name}</text><text x={p.x} y={p.y + 16} textAnchor="middle" fill={zone.status === 'watering' ? '#2769db' : '#688291'} fontSize="11">{zone.status === 'offline' ? '设备离线' : `${zone.crop} · ${number(zone.moisture)}%`}</text>
          <circle cx={p.x + 47} cy={p.y - 22} r="6" fill={zone.status === 'watering' ? '#2769db' : zone.status === 'offline' ? '#a5afb7' : '#2e9c79'} stroke="white" strokeWidth="2" />
        </g>; })}
        <g transform="translate(109 317)"><rect width="36" height="36" rx="10" fill="#2669df" /><path d="M18 7C14 14 10 17 10 22a8 8 0 0 0 16 0c0-5-4-8-8-15" fill="white" /><text x="18" y="52" textAnchor="middle" fontSize="11" fill="#668195">1 号泵站</text></g>
      </g>
    </svg>
    <div className="map-legend"><span><i className="blue" />灌溉中</span><span><i className="green" />待机</span><span><i className="gray" />离线</span></div><span className="map-scale">分区示意 · 非地理测绘</span>
  </div>;
}

function WaterChart({ data, compact = false }: { data: State['history']; compact?: boolean }) {
  return <div className={`chart ${compact ? 'compact' : ''}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 12, right: 12, left: -22, bottom: 0 }}><defs><linearGradient id="water-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3476ec" stopOpacity={.22} /><stop offset="100%" stopColor="#3476ec" stopOpacity={.015} /></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="#e9eef5" /><XAxis dataKey="date" tickFormatter={v => v.slice(5).replace('-', '/')} tickLine={false} axisLine={false} tick={{ fill: '#8390a6', fontSize: 12 }} minTickGap={24} dy={8} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#8390a6', fontSize: 12 }} /><Tooltip labelFormatter={v => `${v} · 模拟记录`} formatter={(v) => [`${number(Number(v))} m³`, '灌溉用水']} contentStyle={{ border: '1px solid #e5edf6', borderRadius: 12, fontSize: 13 }} /><Area type="monotone" dataKey="water" stroke="#2f70e8" strokeWidth={2.6} fill="url(#water-fill)" activeDot={{ r: 5, stroke: 'white', strokeWidth: 3 }} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div>;
}

function IrrigateModal({ zone, state, busy, onClose, mutate }: { zone: Zone; state: State; busy: boolean; onClose: () => void; mutate: Mutation }) {
  const current = state.zones.find(z => z.id === zone.id) ?? zone;
  const [duration, setDuration] = useState(Math.min(20, state.settings.maxDuration));
  const watering = current.status === 'watering';
  async function submit(e: FormEvent) { e.preventDefault(); if (await mutate(`/zones/${current.id}/${watering ? 'stop' : 'start'}`, 'POST', watering ? {} : { duration }, watering ? `${current.name}已停止灌溉` : `${current.name}已开始灌溉`)) onClose(); }
  return <Modal title={watering ? '停止分区灌溉' : '开始分区灌溉'} description="控制指令将发送至本地模拟设备。" onClose={onClose}><form onSubmit={submit}><div className="zone-confirm"><div className="soft-icon"><Drops size={28} /></div><div><h3>{current.name}</h3><p>{current.crop} · {current.area} 亩 · 当前墒情 {number(current.moisture)}%</p></div><Badge status={current.status}>{statusLabels[current.status]}</Badge></div>{!watering && <><label className="field">灌溉时长 <span>分钟</span><input autoFocus type="number" min="1" max={state.settings.maxDuration} step="1" value={duration} onChange={e => setDuration(Number(e.target.value))} required /></label><div className="duration-presets">{[10, 20, 30, 60].filter(v => v <= state.settings.maxDuration).map(v => <button type="button" className={duration === v ? 'selected' : ''} key={v} onClick={() => setDuration(v)}>{v} 分钟</button>)}</div><div className="info-box"><Timer size={20} />到时自动关闭阀门；单次最多 {state.settings.maxDuration} 分钟。</div></>}{watering && <p className="muted">停止后将立即关闭该分区阀门，并保存本次灌溉记录。</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className={`button ${watering ? 'danger' : 'primary'}`} disabled={busy || current.status === 'offline'}>{busy ? '正在执行…' : watering ? '确认停止' : '确认开始灌溉'}</button></div></form></Modal>;
}

function Overview({ state, onPage, onIrrigate, mutate, busy }: { state: State; onPage: (p: Page) => void; onIrrigate: (z: Zone) => void; mutate: Mutation; busy: boolean }) {
  const [selected, setSelected] = useState(state.zones[0]?.id ?? '');
  const [range, setRange] = useState(7);
  const zone = state.zones.find(z => z.id === selected) ?? state.zones[0];
  const active = state.zones.filter(z => z.status === 'watering');
  const online = state.devices.filter(d => d.status === 'online').length;
  const moistureZones = state.zones.filter(z => z.status !== 'offline');
  const moisture = moistureZones.reduce((sum, z) => sum + z.moisture, 0) / (moistureZones.length || 1);
  const alerts = state.alerts.filter(a => !a.acknowledged);
  const today = state.history.at(-1)?.water ?? 0;
  const metrics = [
    { label: '今日灌溉用水', value: number(today), unit: 'm³', icon: Drop, meta: '按本地灌溉记录累计', kind: 'blue' },
    { label: '正在灌溉', value: `${active.length}`, unit: `/ ${state.zones.length} 个分区`, icon: Waves, meta: `覆盖 ${number(active.reduce((n, z) => n + z.area, 0))} 亩农田`, kind: 'cyan' },
    { label: '平均土壤墒情', value: number(moisture), unit: '%', icon: Leaf, meta: `在线分区 · ${moisture < state.settings.moistureThreshold ? '低于预警阈值' : '墒情处于正常范围'}`, kind: 'green' },
    { label: '设备在线率', value: number(online / (state.devices.length || 1) * 100), unit: '%', icon: Radio, meta: `${online} 台在线 / ${state.devices.length} 台设备`, kind: 'violet' },
  ];
  return <><section className="metric-grid">{metrics.map(m => <div className="metric-card" key={m.label}><div className="metric-top"><span>{m.label}</span><div className={`metric-icon ${m.kind}`}><m.icon size={22} weight="duotone" /></div></div><div className="metric-value">{m.value}<span>{m.unit}</span></div><div className="metric-foot"><span className={`tiny-dot ${m.kind}`} />{m.meta}</div></div>)}</section>
    <div className="overview-middle"><section className="panel map-panel"><div className="panel-heading"><div><h2>农场灌溉态势 <span className="count-tag">{state.zones.length} 个分区</span></h2><p>每一块田，都在掌握之中</p></div><button className="text-button" onClick={() => onPage('zones')}>管理分区 <CaretRight size={14} /></button></div><FarmMap zones={state.zones} selected={selected} onSelect={setSelected} />{zone && <div className="selected-zone"><div className="selected-zone-title"><div className="soft-icon small"><Leaf size={21} /></div><div><strong>{zone.name}</strong><span>{zone.crop} · {zone.area} 亩</span></div><Badge status={zone.status}>{statusLabels[zone.status]}</Badge></div><div className="selected-zone-info"><span>土壤墒情<strong>{number(zone.moisture)}<small>%</small></strong></span><span>管道压力<strong>{number(zone.pressure, 2)}<small>MPa</small></strong></span><button className={`button ${zone.status === 'watering' ? 'secondary' : 'primary'} small`} disabled={zone.status === 'offline' || busy} onClick={() => onIrrigate(zone)}>{zone.status === 'watering' ? <Pause size={15} weight="fill" /> : <Play size={15} weight="fill" />}{zone.status === 'watering' ? '停止灌溉' : '开始灌溉'}</button></div></div>}</section>
    <aside className="overview-rail"><section className="weather-panel"><div className="weather-location"><span><MapPin size={14} />{state.farm.location}</span><span className="weather-source">模拟天气</span></div><div className="weather-main"><div><strong>{state.weather.temperature}<sup>°</sup></strong><p>{state.weather.description} <span>适宜田间作业</span></p></div><CloudSun size={70} weight="duotone" /></div><div className="weather-details"><div><Drop size={16} /><span>空气湿度</span><b>{state.weather.humidity}%</b></div><div><Wind size={16} /><span>风速</span><b>{state.weather.wind} m/s</b></div><div><CloudSun size={16} /><span>降雨概率</span><b>{state.weather.rainProbability}%</b></div></div></section><section className="panel attention-panel"><div className="panel-heading"><h2>待关注事项 <span className="alert-count">{alerts.length}</span></h2><button className="icon-button" aria-label="查看所有告警" onClick={() => onPage('alerts')}><ArrowUpRight size={17} /></button></div>{alerts.length ? <div className="attention-list">{alerts.slice(0, 2).map(a => <button className="attention-item" key={a.id} onClick={() => onPage('alerts')}><span className={`alert-icon ${a.level}`}><Warning size={18} /></span><span><strong>{a.title}</strong><small>{state.zones.find(z => z.id === a.zoneId)?.name ?? '农场设备'} · {time(a.createdAt)}</small></span><CaretRight size={14} /></button>)}</div> : <div className="quiet-state"><ShieldCheck size={22} />当前暂无未处理告警</div>}<div className="attention-tip"><ShieldCheck size={15} />及时巡检，让每一次灌溉更安心</div></section></aside></div>
    <div className="overview-bottom"><section className="panel"><div className="panel-heading"><div><h2>灌溉用水趋势</h2><p>每日用水量 <span className="unit-tag">m³</span></p></div><div className="segmented">{[7, 14].map(v => <button key={v} className={range === v ? 'active' : ''} onClick={() => setRange(v)}>近 {v} 天</button>)}</div></div><WaterChart data={state.history.slice(-range)} compact /><div className="chart-footer"><span><i />灌溉用水</span><button className="text-button" onClick={() => onPage('analytics')}>查看用水分析 <CaretRight size={14} /></button></div></section><section className="panel schedule-panel"><div className="panel-heading"><div><h2>灌溉计划</h2><p>{state.plans.filter(p => p.enabled).length} 个计划已启用 · 北京时间</p></div><button className="text-button" onClick={() => onPage('plans')}>全部计划 <CaretRight size={14} /></button></div><div className="schedule-list">{state.plans.slice(0, 3).map(plan => <div className="schedule-row" key={plan.id}><div className="schedule-time">{plan.startTime}<span>{plan.days.length === 7 ? '每天' : plan.days.map(d => week[d - 1].slice(1)).join(' / ')}</span></div><div className="schedule-line"><i /></div><div className="schedule-detail"><strong>{plan.name}</strong><span>{plan.zoneIds.length} 个分区 · {plan.duration} 分钟</span></div><button className={`switch ${plan.enabled ? 'on' : ''}`} role="switch" aria-checked={plan.enabled} aria-label={`${plan.enabled ? '停用' : '启用'}${plan.name}`} disabled={busy} onClick={() => mutate(`/plans/${plan.id}`, 'PATCH', { enabled: !plan.enabled }, plan.enabled ? '计划已暂停' : '计划已启用')}><i /></button></div>)}{!state.plans.length && <Empty text="还没有灌溉计划" />}</div><button className="schedule-add" onClick={() => onPage('plans')}><Plus size={16} />管理自动灌溉计划</button></section></div>
  </>;
}

function Zones({ state, search, onIrrigate, busy }: { state: State; search: string; onIrrigate: (z: Zone) => void; busy: boolean }) {
  const [filter, setFilter] = useState('all');
  const [query, setQuery] = useState(search);
  useEffect(() => setQuery(search), [search]);
  const filtered = state.zones.filter(z => (filter === 'all' || z.status === filter) && `${z.name}${z.crop}${z.deviceId}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="section-toolbar"><div className="filter-tabs">{[['all', '全部分区'], ['watering', '灌溉中'], ['idle', '待机'], ['offline', '离线']].map(([id, label]) => <button className={filter === id ? 'active' : ''} key={id} onClick={() => setFilter(id)}>{label}<span>{id === 'all' ? state.zones.length : state.zones.filter(z => z.status === id).length}</span></button>)}</div><label className="search-field"><Search size={17} /><input placeholder="搜索分区、作物或设备" value={query} onChange={e => setQuery(e.target.value)} /></label></div><div className="zone-grid">{filtered.map((z, index) => { const session = state.sessions.find(s => s.zoneId === z.id && ['running', 'active', 'watering'].includes(s.status)); return <section className={`panel zone-card ${z.status}`} key={z.id}><div className="zone-card-top"><span className="zone-number">{String(state.zones.indexOf(z) + 1).padStart(2, '0')}</span><Badge status={z.status}>{statusLabels[z.status]}</Badge></div><h2>{z.name}</h2><p className="zone-crop"><Leaf size={15} />{z.crop}<span />{z.area} 亩</p><div className="moisture-heading"><span>土壤墒情</span><strong>{number(z.moisture)}<small>%</small></strong></div><div className="moisture-track"><span style={{ width: `${Math.min(100, z.moisture)}%` }} /><i style={{ left: `${z.targetMoisture}%` }} /></div><div className="moisture-caption"><span>当前墒情</span><span>目标 {z.targetMoisture}%</span></div><div className="zone-measures"><div><Gauge size={19} /><span>管道压力</span><strong>{number(z.pressure, 2)} <small>MPa</small></strong></div><div><Waves size={19} /><span>瞬时流量</span><strong>{number(z.flow)} <small>L/min</small></strong></div></div><div className="zone-card-bottom"><span>{z.status === 'offline' ? '请检查设备连接' : session ? `预计 ${time(session.endsAt)} 结束` : `设备 ${z.deviceId}`}</span><button className={`button ${z.status === 'watering' ? 'secondary' : 'primary'} small`} disabled={busy || z.status === 'offline'} onClick={() => onIrrigate(z)}>{z.status === 'watering' ? <Pause size={15} weight="fill" /> : <Play size={15} weight="fill" />}{z.status === 'watering' ? '停止' : '灌溉'}</button></div></section>; })}</div>{!filtered.length && <Empty text="未找到匹配的分区"><p>试试其他关键词或筛选条件。</p></Empty>}<div className="page-note"><Info size={16} />墒情来自模拟传感器。离线分区显示最后一次读数，暂停控制。</div></>;
}

function Devices({ state }: { state: State }) {
  const [filter, setFilter] = useState('all');
  const [query, setQuery] = useState('');
  const [detail, setDetail] = useState<string | null>(null);
  const devices = state.devices.filter(d => (filter === 'all' || d.status === filter) && `${d.name}${d.id}`.toLowerCase().includes(query.toLowerCase()));
  const selected = state.devices.find(d => d.id === detail);
  return <><div className="summary-strip"><div><Radio size={25} /><span>设备总数<strong>{state.devices.length}<small>台</small></strong></span></div><div><WifiHigh size={25} /><span>在线设备<strong>{state.devices.filter(d => d.status === 'online').length}<small>台</small></strong></span></div><div><WifiSlash size={25} /><span>离线设备<strong>{state.devices.filter(d => d.status === 'offline').length}<small>台</small></strong></span></div></div><section className="panel table-panel"><div className="section-toolbar inside"><div className="filter-tabs">{[['all', '全部设备'], ['online', '在线'], ['offline', '离线']].map(([id, label]) => <button key={id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)}>{label}</button>)}</div><label className="search-field"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索设备名称或编号" /></label></div><div className="table-scroll"><table><thead><tr><th>设备名称 / 编号</th><th>所属分区</th><th>状态</th><th>电量</th><th>信号</th><th>最近通信</th><th>操作</th></tr></thead><tbody>{devices.map(d => <tr key={d.id}><td><div className="device-name"><span className="soft-icon small"><Cpu size={21} /></span><span><strong>{d.name}</strong><small>{d.id} · {d.type}</small></span></div></td><td>{state.zones.find(z => z.id === d.zoneId)?.name ?? '公共设备'}</td><td><Badge status={d.status}>{d.status === 'online' ? '在线' : '离线'}</Badge></td><td><div className="battery"><i><span style={{ width: `${d.battery}%` }} /></i>{d.battery}%</div></td><td><span className="signal"><WifiHigh size={17} />{d.signal}%</span></td><td>{dateTime(d.lastSeen)}</td><td><button className="text-button" onClick={() => setDetail(d.id)}>详情</button></td></tr>)}</tbody></table></div>{!devices.length && <Empty text="没有匹配的设备" />}<div className="table-footer">共 {devices.length} 台设备<span>本地模拟设备 · 每 5 秒刷新</span></div></section>{selected && <Modal title="设备详情" description={selected.id} onClose={() => setDetail(null)}><div className="detail-grid">{[['设备名称', selected.name], ['设备类型', selected.type], ['所属分区', state.zones.find(z => z.id === selected.zoneId)?.name ?? '公共设备'], ['在线状态', selected.status === 'online' ? '在线' : '离线'], ['电池电量', `${selected.battery}%`], ['信号强度', `${selected.signal}%`], ['最后通信', dateTime(selected.lastSeen)], ['数据来源', '本地模拟器']].map(([k, v]) => <div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="info-box"><Info size={20} />接入真实硬件时，可在后端设备适配层接入 MQTT 或 HTTP 上报。</div></Modal>}</>;
}

function PlanForm({ state, plan, mutate, busy, onClose }: { state: State; plan?: Plan; mutate: Mutation; busy: boolean; onClose: () => void }) {
  const [name, setName] = useState(plan?.name ?? '');
  const [startTime, setStartTime] = useState(plan?.startTime ?? '06:30');
  const [duration, setDuration] = useState(plan?.duration ?? Math.min(20, state.settings.maxDuration));
  const [days, setDays] = useState(plan?.days ?? [1, 2, 3, 4, 5, 6, 7]);
  const [zoneIds, setZoneIds] = useState<string[]>(plan?.zoneIds ?? []);
  const [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); if (!zoneIds.length || !days.length) { setError('请选择至少一个分区和一个执行日期。'); return; } if (await mutate(plan ? `/plans/${plan.id}` : '/plans', plan ? 'PUT' : 'POST', { name: name.trim(), startTime, duration, days, zoneIds, enabled: plan?.enabled ?? true }, plan ? '灌溉计划已更新' : '灌溉计划已创建')) onClose(); }
  return <Modal title={plan ? '编辑灌溉计划' : '新建灌溉计划'} description="计划按北京时间执行，本地服务需保持运行。" onClose={onClose}><form onSubmit={submit}><label className="field">计划名称<input autoFocus value={name} maxLength={40} onChange={e => setName(e.target.value)} required placeholder="例如：东区清晨滴灌" /></label><div className="form-row"><label className="field">开始时间<input type="time" value={startTime} onInput={e => setStartTime(e.currentTarget.value)} onChange={e => setStartTime(e.target.value)} required /></label><label className="field">持续时长（分钟）<input type="number" value={duration} onChange={e => setDuration(Number(e.target.value))} min="1" max={state.settings.maxDuration} step="1" required /></label></div><div className="field"><span>重复日期</span><div className="week-picker">{week.map((d, i) => <button key={d} type="button" aria-pressed={days.includes(i + 1)} className={days.includes(i + 1) ? 'selected' : ''} onClick={() => setDays(days.includes(i + 1) ? days.filter(v => v !== i + 1) : [...days, i + 1].sort())}>{d}</button>)}</div></div><div className="field"><span>执行分区</span><div className="zone-picker">{state.zones.map(z => <label key={z.id} className={zoneIds.includes(z.id) ? 'selected' : ''}><input type="checkbox" checked={zoneIds.includes(z.id)} onChange={() => setZoneIds(zoneIds.includes(z.id) ? zoneIds.filter(id => id !== z.id) : [...zoneIds, z.id])} /><span>{z.name}<small>{z.crop}{z.status === 'offline' ? ' · 离线时跳过' : ''}</small></span></label>)}</div></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy || !name.trim()}>{busy ? '正在保存…' : '保存计划'}</button></div></form></Modal>;
}

function Plans({ state, mutate, busy }: { state: State; mutate: Mutation; busy: boolean }) {
  const [editing, setEditing] = useState<Plan | 'new' | null>(null);
  const [deleting, setDeleting] = useState<Plan | null>(null);
  return <><div className="feature-banner"><div className="feature-icon"><CalendarBlank size={30} weight="duotone" /></div><div><h2>把日常灌溉，交给计划</h2><p>按分区、时间与周期自动执行，让田间管理更有序。</p></div><button className="button primary" onClick={() => setEditing('new')} disabled={busy}><Plus size={17} />新建计划</button></div><div className="plan-grid">{state.plans.map(p => <section className="panel plan-card" key={p.id}><div className="plan-card-heading"><span className="soft-icon"><CalendarBlank size={24} /></span><Badge status={p.enabled ? 'online' : 'idle'}>{p.enabled ? '已启用' : '已暂停'}</Badge></div><h2>{p.name}</h2><div className="plan-main-time">{p.startTime}<span><Timer size={15} />{p.duration} 分钟</span></div><div className="plan-days">{week.map((d, i) => <span key={d} className={p.days.includes(i + 1) ? 'selected' : ''}>{d.slice(1)}</span>)}</div><div className="plan-zones"><MapPin size={16} /><span>{p.zoneIds.map(id => state.zones.find(z => z.id === id)?.name).filter(Boolean).join('、')}</span></div><div className="plan-last">最近执行：{p.lastRun ? dateTime(p.lastRun) : '尚未执行'}</div><div className="plan-card-actions"><button className={`switch ${p.enabled ? 'on' : ''}`} role="switch" aria-checked={p.enabled} aria-label={`${p.enabled ? '暂停' : '启用'}${p.name}`} disabled={busy} onClick={() => mutate(`/plans/${p.id}`, 'PATCH', { enabled: !p.enabled }, p.enabled ? '计划已暂停' : '计划已启用')}><i /></button><span>{p.enabled ? '自动执行' : '暂停执行'}</span><button className="text-button" disabled={busy} onClick={() => setEditing(p)}>编辑</button><button className="icon-button" aria-label={`删除${p.name}`} disabled={busy} onClick={() => setDeleting(p)}><Trash size={17} /></button></div></section>)}</div>{!state.plans.length && <Empty text="创建第一个灌溉计划"><p>为不同作物设置适合的灌溉周期。</p></Empty>}<div className="page-note"><Info size={16} />离线或正在灌溉的分区会跳过执行并写入日志；关闭电脑期间的计划不会补灌。</div>{editing && <PlanForm state={state} plan={editing === 'new' ? undefined : editing} mutate={mutate} busy={busy} onClose={() => setEditing(null)} />}{deleting && <Modal title="删除灌溉计划" onClose={() => setDeleting(null)}><p>确定删除“{deleting.name}”？正在进行的灌溉不会受到影响。</p><div className="dialog-actions"><button className="button secondary" onClick={() => setDeleting(null)}>取消</button><button className="button danger" disabled={busy} onClick={async () => { if (await mutate(`/plans/${deleting.id}`, 'DELETE', undefined, '计划已删除')) setDeleting(null); }}>确认删除</button></div></Modal>}</>;
}

function Alerts({ state, mutate, busy }: { state: State; mutate: Mutation; busy: boolean }) {
  const [filter, setFilter] = useState('pending');
  const [tab, setTab] = useState('alerts');
  const filtered = state.alerts.filter(a => filter === 'all' || (filter === 'pending' ? !a.acknowledged : a.acknowledged));
  return <><div className="summary-strip"><div><Warning size={25} /><span>待处理告警<strong>{state.alerts.filter(a => !a.acknowledged).length}<small>条</small></strong></span></div><div><ShieldCheck size={25} /><span>已确认告警<strong>{state.alerts.filter(a => a.acknowledged).length}<small>条</small></strong></span></div><div><Clock size={25} /><span>操作记录<strong>{state.logs.length}<small>条</small></strong></span></div></div><section className="panel"><div className="section-toolbar inside"><div className="filter-tabs"><button className={tab === 'alerts' ? 'active' : ''} onClick={() => setTab('alerts')}>设备与灌溉告警</button><button className={tab === 'logs' ? 'active' : ''} onClick={() => setTab('logs')}>操作日志</button></div>{tab === 'alerts' && <select aria-label="筛选告警状态" value={filter} onChange={e => setFilter(e.target.value)}><option value="pending">待处理</option><option value="done">已确认</option><option value="all">全部告警</option></select>}</div>{tab === 'alerts' ? <div className="alerts-list">{filtered.map(a => <div className={`alert-row ${a.acknowledged ? 'acknowledged' : ''}`} key={a.id}><span className={`alert-icon ${a.level}`}><Warning size={23} /></span><div><div className="alert-title"><h3>{a.title}</h3><span className={`level ${a.level}`}>{a.level === 'critical' ? '严重' : a.level === 'warning' ? '预警' : '提示'}</span></div><p>{a.detail}</p><small>{state.zones.find(z => z.id === a.zoneId)?.name ?? '系统'} · {dateTime(a.createdAt)}</small></div>{a.acknowledged ? <span className="ack-label"><CheckCircle size={17} />已确认</span> : <button className="button secondary small" disabled={busy} onClick={() => mutate(`/alerts/${a.id}/ack`, 'POST', {}, '告警已确认，设备状态请继续关注')}>确认告警</button>}</div>)}{!filtered.length && <Empty text={filter === 'pending' ? '暂无待处理告警' : '暂无告警记录'}><p>设备与灌溉异常会显示在这里。</p></Empty>}</div> : <div className="log-list">{state.logs.map(log => <div className="log-row" key={log.id}><span className="log-dot" /><div><p>{log.message}</p><small>{dateTime(log.createdAt)}</small></div><span className="log-type">{log.type === 'control' ? '灌溉控制' : log.type === 'plan' ? '计划管理' : log.type === 'alert' ? '告警处理' : log.type === 'system' ? '系统' : log.type}</span></div>)}{!state.logs.length && <Empty text="暂无操作记录" />}</div>}</section><div className="page-note"><Info size={16} />确认告警表示已知悉，不会自动修复设备或清除异常状态。</div></>;
}

function Analytics({ state }: { state: State }) {
  const [days, setDays] = useState(7);
  const data = state.history.slice(-days);
  const total = data.reduce((n, d) => n + d.water, 0);
  return <><div className="section-toolbar"><div className="filter-tabs">{[7, 14, 30].map(v => <button key={v} className={days === v ? 'active' : ''} onClick={() => setDays(v)}>近 {v} 天</button>)}</div><a className="button secondary" href="/api/export.csv" download><DownloadSimple size={17} />导出全部记录</a></div><div className="summary-strip"><div><Drop size={26} /><span>期间累计用水<strong>{number(total)}<small>m³</small></strong></span></div><div><ChartLineUp size={26} /><span>日均灌溉用水<strong>{number(total / (data.length || 1))}<small>m³</small></strong></span></div><div><Leaf size={26} /><span>亩均用水<strong>{number(total / state.farm.area, 2)}<small>m³ / 亩</small></strong></span></div></div><section className="panel"><div className="panel-heading"><div><h2>灌溉用水趋势</h2><p>{data[0]?.date} 至 {data.at(-1)?.date} · 单位 m³</p></div><span className="data-label"><i />本地模拟数据</span></div><WaterChart data={data} /></section><div className="analytics-bottom"><section className="panel"><div className="panel-heading"><div><h2>平均土壤墒情变化</h2><p>每日平均值 · 单位 %</p></div></div><div className="chart compact"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 10, right: 18, left: -22, bottom: 0 }}><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="#e9eef5" /><XAxis dataKey="date" tickFormatter={v => v.slice(5).replace('-', '/')} tickLine={false} axisLine={false} minTickGap={20} tick={{ fill: '#8390a6', fontSize: 12 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#8390a6', fontSize: 12 }} /><Tooltip formatter={v => [`${v}%`, '平均墒情']} /><Bar dataKey="moisture" fill="#85b3f4" radius={[5, 5, 0, 0]} maxBarSize={26} isAnimationActive={false} /></BarChart></ResponsiveContainer></div></section><section className="panel records-panel"><div className="panel-heading"><h2>每日用水记录</h2><span className="count-tag">{data.length} 天</span></div><div className="records-scroll"><table><thead><tr><th>日期</th><th>用水量</th><th>平均墒情</th></tr></thead><tbody>{[...data].reverse().map(row => <tr key={row.date}><td>{row.date}</td><td>{number(row.water)} m³</td><td>{number(row.moisture)}%</td></tr>)}</tbody></table></div></section></div><div className="page-note"><Info size={16} />初始历史记录为演示数据；后续用水量按模拟流量与实际运行时长累计。</div></>;
}

function SettingsPage({ state, mutate, busy }: { state: State; mutate: Mutation; busy: boolean }) {
  const [form, setForm] = useState<Settings>({ ...state.settings });
  async function save(e: FormEvent) { e.preventDefault(); await mutate('/settings', 'PUT', form, '农场设置已保存'); }
  return <div className="settings-layout"><form className="panel settings-form" onSubmit={save}><div className="panel-heading"><div><h2>农场与灌溉设置</h2><p>网页端与小程序共享这些设置</p></div></div><div className="settings-fields"><label className="field">农场名称<input value={form.farmName} maxLength={60} required onChange={e => setForm({ ...form, farmName: e.target.value })} /></label><label className="field">所在地区<input value={form.location} maxLength={120} required onChange={e => setForm({ ...form, location: e.target.value })} /></label><div className="form-row"><label className="field">墒情预警阈值（%）<input type="number" min="0" max="100" step="1" value={form.moistureThreshold} required onChange={e => setForm({ ...form, moistureThreshold: Number(e.target.value) })} /></label><label className="field">单次灌溉上限（分钟）<input type="number" min="1" max="240" step="1" value={form.maxDuration} required onChange={e => setForm({ ...form, maxDuration: Number(e.target.value) })} /></label></div><p className="muted">下调灌溉上限前，请先调整超过上限的灌溉计划。</p><button className="button primary" disabled={busy}>{busy ? '正在保存…' : '保存设置'}</button></div></form><aside><section className="panel connection-panel"><span className="soft-icon"><ShieldCheck size={27} /></span><h2>本地调试环境</h2><p>所有设备指令在模拟器中执行。数据保存在本机，重启后仍可继续使用。</p><dl><div><dt>运行模式</dt><dd>模拟设备</dd></div><div><dt>数据刷新</dt><dd>每 5 秒</dd></div><div><dt>计划时区</dt><dd>Asia/Shanghai</dd></div><div><dt>平台版本</dt><dd>1.0.0</dd></div></dl></section><section className="mini-intro"><Smartphone size={28} /><h3>田间管理，随行掌握</h3><p>配套微信小程序支持查看墒情、控制灌溉、管理计划和处理告警。</p><span>小程序源码位于 miniprogram 目录</span></section></aside></div>;
}

export default function App() {
  const [page, setPage] = useState<Page>(() => { const p = location.hash.slice(1); return [...navigation.map(n => n.id), 'settings'].includes(p) ? p as Page : 'overview'; });
  const [state, setState] = useState<State | null>(null);
  const [connection, setConnection] = useState<'loading' | 'ready' | 'error'>('loading');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const busyRef = useRef(false);
  const requestVersion = useRef(0);
  const [toast, setToast] = useState<{ text: string; error?: boolean } | null>(null);
  const [irrigating, setIrrigating] = useState<Zone | null>(null);
  const [quickStart, setQuickStart] = useState(false);
  const [stopAll, setStopAll] = useState(false);
  const [mobilePreview, setMobilePreview] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [zoneSearch, setZoneSearch] = useState('');
  const mobile = new URLSearchParams(location.search).has('mobile');
  const date = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit', weekday: 'long', timeZone: 'Asia/Shanghai' });
  async function refresh() {
    if (busyRef.current) return;
    const version = ++requestVersion.current;
    try { const next = await api('/state'); if (version !== requestVersion.current) return; setState(next); setConnection('ready'); setError(''); }
    catch (e) { if (version !== requestVersion.current) return; setError((e as Error).message); setConnection('error'); }
  }
  useEffect(() => { refresh(); const interval = setInterval(refresh, 5000); const onHash = () => { const p = location.hash.slice(1); if ([...navigation.map(n => n.id), 'settings'].includes(p)) setPage(p as Page); }; window.addEventListener('hashchange', onHash); return () => { clearInterval(interval); requestVersion.current++; window.removeEventListener('hashchange', onHash); }; }, []);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(null), 5000); return () => clearTimeout(t); }, [toast]);
  const mutate: Mutation = async (path, method = 'POST', body, message = '操作已完成') => {
    if (busyRef.current) return false;
    if (connection !== 'ready') { setToast({ text: '本地服务未连接，请先恢复连接', error: true }); return false; }
    busyRef.current = true; setBusy(true); requestVersion.current++;
    try { const result = await api(path, method, body); setState(result); setToast({ text: message }); return true; }
    catch (e) { setToast({ text: (e as Error).message, error: true }); return false; }
    finally { busyRef.current = false; setBusy(false); }
  };
  function go(p: Page) { setPage(p); location.hash = p; setSidebarOpen(false); window.scrollTo({ top: 0, behavior: 'instant' }); }
  const disabled = busy || connection !== 'ready';
  const current = navigation.find(n => n.id === page)?.label ?? '平台设置';
  const titles: Record<Page, [string, string]> = {
    decision: ['灌溉决策', '结合蒸散、降雨与作物阶段，估算单日补水需求。'],
    overview: ['农场运行总览', '感知田间每一刻，让每一滴水恰到好处。'], zones: ['分区灌溉', '了解每一块田的状态，按需开启精准灌溉。'], devices: ['设备管理', '从传感器到阀门，设备状态一目了然。'], plans: ['灌溉计划', '有序安排每一次灌溉。'], analytics: ['用水分析', '从每一天的记录中，了解农场的用水情况。'], alerts: ['告警中心', '及时发现异常，跟进每一次设备与灌溉事件。'], settings: ['平台设置', '为你的农场，设置合适的管理方式。'],
  };
  if (!state) return <div className="boot-screen"><Brand /><div className="boot-card">{connection === 'error' ? <><Warning size={38} /><h1>暂时无法连接本地服务</h1><p>{error}</p><button className="button primary" onClick={refresh}><ArrowClockwise size={17} />重新连接</button><small>在项目目录执行 npm run dev 启动平台与模拟服务。</small></> : <><div className="loader" /><h1>正在连接智慧农场</h1><p>读取分区、设备与灌溉记录…</p></>}</div></div>;
  const pending = state.alerts.filter(a => !a.acknowledged).length;
  const running = state.zones.filter(z => z.status === 'watering').length;
  return <div className={`app ${mobile ? 'mobile-mode' : ''}`}>
    {sidebarOpen && <button className="sidebar-scrim" aria-label="关闭导航" onClick={() => setSidebarOpen(false)} />}
    <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><Brand /><div className="workspace-label">农场工作空间</div><nav>{navigation.map(n => <button key={n.id} className={page === n.id ? 'active' : ''} onClick={() => go(n.id)}><n.icon size={21} weight={page === n.id ? 'fill' : 'regular'} /><span>{n.label}</span>{n.id === 'alerts' && pending > 0 && <b>{pending}</b>}{page === n.id && <i />}</button>)}</nav><div className="sidebar-bottom"><button className="mobile-preview-entry" onClick={() => setMobilePreview(true)}><div className="phone-icon"><Smartphone size={27} weight="duotone" /></div><div><strong>掌上智慧农场</strong><span>查看移动端预览</span></div><CaretRight size={15} /></button><button className={`settings-nav ${page === 'settings' ? 'active' : ''}`} onClick={() => go('settings')}><GearSix size={21} />平台设置</button><div className="sidebar-env"><span /><span>本地调试环境<small>LOCAL WORKSPACE · V1.0</small></span><ShieldCheck size={18} /></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button hamburger" aria-label="展开导航" onClick={() => setSidebarOpen(true)}><List size={23} /></button><House size={17} /><span>工作空间</span><CaretRight size={12} /><strong>{current}</strong></div><div className="topbar-right"><form className="global-search" onSubmit={e => { e.preventDefault(); setZoneSearch(search); go('zones'); }}><Search size={17} /><input aria-label="搜索农场分区" placeholder="搜索农场分区…" value={search} onChange={e => setSearch(e.target.value)} /><kbd>Enter</kbd></form><span className="topbar-divider" /><button className="notification-button icon-button" aria-label={`告警中心，${pending}条待处理`} onClick={() => go('alerts')}><Bell size={21} />{pending > 0 && <i />}</button><button className="profile" onClick={() => go('settings')}><span className="avatar">管</span><span>农场管理员<small>本地工作空间</small></span><CaretDown size={12} /></button></div></header>
    <main><div className="farm-context"><span><span className="farm-dot" />{state.farm.name}</span><span className="context-separator">/</span><span>{number(state.farm.area)} 亩</span><span className={`connection ${connection}`}><i />{connection === 'ready' ? '本地服务已连接' : '服务连接中断'}</span></div><div className="page-heading"><div><h1>{titles[page][0]}</h1><p>{titles[page][1]}</p></div><div className="heading-actions">{page === 'overview' ? <><span className="date-label"><CalendarBlank size={16} />{date}</span><button className="button primary" disabled={disabled} onClick={() => setQuickStart(true)}><Plus size={17} />新建灌溉</button></> : <button className="button secondary" disabled={busy} onClick={refresh}><ArrowClockwise size={16} />刷新数据</button>}</div></div>
    {connection === 'error' && <div className="connection-error" role="alert"><Warning size={20} /><span>{error}。当前显示最后一次同步数据，控制已暂停。</span><button onClick={refresh}>重新连接</button></div>}
    {page === 'overview' && <Overview state={state} onPage={go} onIrrigate={setIrrigating} mutate={mutate} busy={disabled} />}
    {page === 'zones' && <Zones state={state} search={zoneSearch} onIrrigate={setIrrigating} busy={disabled} />}
    {page === 'decision' && <Decision state={state} disabled={disabled} onIrrigate={setIrrigating} />}
    {page === 'devices' && <Devices state={state} />}
    {page === 'plans' && <Plans state={state} mutate={mutate} busy={disabled} />}
    {page === 'analytics' && <Analytics state={state} />}
    {page === 'alerts' && <Alerts state={state} mutate={mutate} busy={disabled} />}
    {page === 'settings' && <SettingsPage state={state} mutate={mutate} busy={disabled} />}
    <footer><span><span className="footer-brand">LANSHU</span>澜枢智慧灌溉<span className="footer-divider">|</span>本地模拟数据</span><span>最近同步 {time(state.updatedAt)}<span className="footer-divider">·</span><button onClick={() => setStopAll(true)} disabled={!running || disabled}><Power size={13} />停止全部灌溉{running ? ` (${running})` : ''}</button></span></footer></main></div>
    <nav className="mobile-bottom-nav">{navigation.filter(n => ['overview', 'zones', 'plans', 'alerts'].includes(n.id)).map(n => <button key={n.id} className={page === n.id ? 'active' : ''} onClick={() => go(n.id)}><n.icon size={22} weight={page === n.id ? 'fill' : 'regular'} /><span>{n.label.replace('运行', '').replace('分区', '').replace('灌溉计划', '计划').replace('中心', '')}</span></button>)}<button className={page === 'settings' ? 'active' : ''} onClick={() => go('settings')}><GearSix size={22} /><span>我的</span></button></nav>
    {toast && <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <Warning size={20} /> : <CheckCircle size={20} weight="fill" />}<span>{toast.text}</span><button aria-label="关闭提示" onClick={() => setToast(null)}><X size={15} /></button></div>}
    {irrigating && <IrrigateModal zone={irrigating} state={state} busy={disabled} mutate={mutate} onClose={() => setIrrigating(null)} />}
    {quickStart && <Modal title="选择灌溉分区" description="选择一个分区，设置本次灌溉时长。" onClose={() => setQuickStart(false)}><div className="quick-zones">{state.zones.map(z => <button key={z.id} disabled={z.status === 'offline' || disabled} onClick={() => { setQuickStart(false); setIrrigating(z); }}><span className="soft-icon small"><Leaf size={20} /></span><span><strong>{z.name}</strong><small>{z.crop} · {z.area} 亩</small></span><Badge status={z.status}>{statusLabels[z.status]}</Badge><CaretRight size={16} /></button>)}</div></Modal>}
    {stopAll && <Modal title="停止全部灌溉" description={`当前共有 ${running} 个分区正在灌溉。`} onClose={() => setStopAll(false)}><p>确认后将立即关闭所有正在灌溉的模拟阀门，并保存运行记录。已启用的定时计划保持原设置。</p><div className="dialog-actions"><button className="button secondary" onClick={() => setStopAll(false)}>取消</button><button className="button danger" disabled={disabled} onClick={async () => { if (await mutate('/stop-all', 'POST', {}, '所有分区已停止灌溉')) setStopAll(false); }}>确认全部停止</button></div></Modal>}
    {mobilePreview && <Modal title="掌上智慧农场" description="移动网页版预览；配套原生微信小程序源码已单独提供。" onClose={() => setMobilePreview(false)} wide><div className="phone-preview"><iframe src="/?mobile=1" title="澜枢移动端交互预览" /></div></Modal>}
  </div>;
}
